# Generated by Django 5.0.7 on 2024-08-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_tag_post_category_post_tags_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
